name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
     
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: DJansen_CV.tex
          extra_fonts: ./fonts/FontAwesome.ttf
          latexmk_use_xelatex: true
      - name: Commit report
        run: |
          git config --global user.name 'David Jansen'
          git config --global user.email 'david-awam-jansen@users.noreply.github.com'
          git add DJansen_CV.pdf
          git commit -m "Automated update to pdf"
          git push
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'David Jansen'
          destination-repository-name: 'presentations/pdf'
          user-email: david.awam.jansen@gmail.com
          target-branch: main

