name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
     
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: my_test.tex
          - name: Commit report
      run: |
        git config --global user.name 'David Jansen'
        git config --global user.email 'david-awam-jansen@users.noreply.github.com'
        git commit -am "Automated update to pdf"
        git push
