name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: my_test.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: DJansen_CV.pdf
      - name: Check dir
        run: |
          ls -lh
      - name: upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: DJansen_CV.pdf
